# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
