# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bowling_app', '0004_auto_20180328_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bowling_app.Game'),
        ),
    ]
