# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling_app', '0006_game_running_total_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_score', models.IntegerField(default=0)),
            ],
        ),
    ]
