# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bowling_app', '0007_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='game',
        ),
        migrations.AddField(
            model_name='frame',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bowling_app.Game'),
        ),
        migrations.AddField(
            model_name='roll',
            name='frame',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bowling_app.Frame'),
        ),
    ]
