# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling_app', '0008_auto_20180328_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_frame',
            field=models.SmallIntegerField(default=0),
        ),
    ]
