# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling_app', '0013_auto_20180329_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='frame_id_offset',
            field=models.IntegerField(default=0),
        ),
    ]
